//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompassionWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CompassionDBEntities : DbContext
    {
        public CompassionDBEntities()
            : base("name=CompassionDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Beneficiarios> Tb_Beneficiarios { get; set; }
        public virtual DbSet<Tb_CDI> Tb_CDI { get; set; }
        public virtual DbSet<Tb_ActividadesPrincipales> Tb_ActividadesPrincipales { get; set; }
        public virtual DbSet<Tb_ActividadesSecundarias> Tb_ActividadesSecundarias { get; set; }
        public virtual DbSet<Tb_Categorias> Tb_Categorias { get; set; }
        public virtual DbSet<Tb_EjesEstrategicos> Tb_EjesEstrategicos { get; set; }
        public virtual DbSet<Tb_PrecondicionesTOC> Tb_PrecondicionesTOC { get; set; }
        public virtual DbSet<Tb_Resultados> Tb_Resultados { get; set; }
        public virtual DbSet<Tb_ActividadesBeneficiarios> Tb_ActividadesBeneficiarios { get; set; }
        public virtual DbSet<Tb_ActividadesDetalles> Tb_ActividadesDetalles { get; set; }
        public virtual DbSet<Tb_Usuarios> Tb_Usuarios { get; set; }
        public virtual DbSet<Tb_Plantillas> Tb_Plantillas { get; set; }
        public virtual DbSet<Tb_InscripcionActividad> Tb_InscripcionActividad { get; set; }
    }
}
