//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompassionWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_ActividadesDetalles
    {
        public int ID_detalleActividad { get; set; }
        public int ID_recurso { get; set; }
        public string ValorTexto { get; set; }
        public decimal ValorNumerico { get; set; }
        public int ValorEntero { get; set; }
        public string Descripcion { get; set; }
        public bool Original { get; set; }
        public int ID_actividadSecundaria { get; set; }
        public int ID_actividadBeneficiario { get; set; }
        public string Parametro { get; set; }
        public string ValorMultipleOpciones { get; set; }
        public decimal ValorMax { get; set; }
        public decimal ValorMin { get; set; }
        public int ID_plantilla { get; set; }
        public int Orden { get; set; }
    }
}
