//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompassionWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_ActividadesBeneficiarios
    {
        public int ID_actividadBeneficiario { get; set; }
        public string LocalBeneficiaryID { get; set; }
        public string FCPID { get; set; }
        public int ID_eje { get; set; }
        public int ID_categoria { get; set; }
        public int ID_actividadPrincipal { get; set; }
        public int ID_actividadSecundaria { get; set; }
        public int ID_resultado { get; set; }
        public int ID_precondicionTOC { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime Fecha_actualizacion { get; set; }
        public string Comentarios { get; set; }
        public int ID_usuario { get; set; }
        public int ID_plantilla { get; set; }
        public int parent { get; set; }
        public bool masiva { get; set; }
    
        public virtual Tb_ActividadesPrincipales Tb_ActividadesPrincipales { get; set; }
        public virtual Tb_ActividadesSecundarias Tb_ActividadesSecundarias { get; set; }
        public virtual Tb_Beneficiarios Tb_Beneficiarios { get; set; }
        public virtual Tb_Categorias Tb_Categorias { get; set; }
        public virtual Tb_CDI Tb_CDI { get; set; }
        public virtual Tb_EjesEstrategicos Tb_EjesEstrategicos { get; set; }
        public virtual Tb_PrecondicionesTOC Tb_PrecondicionesTOC { get; set; }
        public virtual Tb_Resultados Tb_Resultados { get; set; }
        public virtual Tb_Categorias Tb_Categorias1 { get; set; }
        public virtual Tb_PrecondicionesTOC Tb_PrecondicionesTOC1 { get; set; }
        public virtual Tb_Usuarios Tb_Usuarios { get; set; }
    }
}
