//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompassionWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Beneficiarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Beneficiarios()
        {
            this.Tb_ActividadesBeneficiarios = new HashSet<Tb_ActividadesBeneficiarios>();
        }
    
        public string BeneficiaryICPID { get; set; }
        public string LocalBeneficiaryID { get; set; }
        public string ChronicIllnesses { get; set; }
        public string TypeOfVocational_TechTraining { get; set; }
        public string FormalEducationLevel { get; set; }
        public bool BeneficiaryConfessesJesusasSavior { get; set; }
        public string SponsorshipStatus { get; set; }
        public string AccountName { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
        public string Tutor_ImplementerName { get; set; }
        public string Classroom_CDPRAgeGroup { get; set; }
        public string Household { get; set; }
        public string BeneficiaryStatus { get; set; }
        public string BeneficiaryCluster { get; set; }
        public string State_Province { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_ActividadesBeneficiarios> Tb_ActividadesBeneficiarios { get; set; }
    }
}
