//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompassionWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Usuarios()
        {
            this.Tb_ActividadesBeneficiarios = new HashSet<Tb_ActividadesBeneficiarios>();
        }
    
        public int ID_usuario { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Nombre_completo { get; set; }
        public string Pais { get; set; }
        public System.DateTime Created { get; set; }
        public string Roles { get; set; }
        public string URL_image { get; set; }
        public bool Active { get; set; }
        public string CDI { get; set; }
        public string PeriodosActivos { get; set; }
        public Nullable<System.DateTime> FechaInicioPeriodos { get; set; }
        public Nullable<System.DateTime> FechaFinalPeriodos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_ActividadesBeneficiarios> Tb_ActividadesBeneficiarios { get; set; }
    }
}
